name: Publish Extension
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14
      - name: Install vsce
        run: npm install -g vsce
      - name: Install dependencies
        run: npm install
      - name: Build extension
        run: npm run compile
      - name: Publish extension
        run: vsce publish -p ${{ secrets.AZURE_DEVOPS_PAT }}
